### ISSUE TITLE
Definir contenidos a convertir en JSON-LD y organizar carpetas

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [opendata-euskadi/schema.org#4]

**Comment by imanol-argueso** [comment]
Subidos a Sharepoint 3 listados (Documentos/Producto/Datos):
- El listado de tipos de contenido a convertir a Schema (debatido en la reunión del 29/12/16 y modificado según lo acordado).
- El listado de tipos de contenido que además van a la triple store (a comentar en la próxima reunión).
- El listado de datasets que van a la triple store mediante el conector (a comentar en la próxima reunión).

**Comment by mikel-egana-aranguren** [comment]
Eskerrik asko @imanol-argueso 

Creo que el listado 3 (datasets que van a la triple store mediante conector) habría que añadirlo como issue en otro repositorio de https://github.com/opendata-euskadi, ya que este repositorio es para JSON-LD/Schema.org. @futuretelematics puedes crear otro repo para CSVs? Ahí podemos subir, por ejemplo, el trabajo que hemos hecho ya de convertir calidad de aire a RDF.
